packages:
  - "."
  - "practices/*"

catalog:
  "@babel/parser": ^7.29.7
  "@rspress/core": ^2.0.14
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.1
  "@shikijs/transformers": ^4.2.0
  "jsdom": ^27.3.0
  "react": ^19.2.0
  "react-dom": ^19.2.0
  "react-router-dom": ^7.10.1
  "typescript": ^5.9.3
  "vite": ^7.2.6
  "vitest": ^4.0.15

allowBuilds:
  esbuild: true
